name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error at step '...'
        3. Error message '...'
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        - PLINK version: [e.g., 1.90b3w]
        - Operating System: [e.g., Linux, CentOS 7]
        - Python version: [e.g., 3.8.5]
        - Number of SNPs: [e.g., 926,030]
        - Number of Individuals: [e.g., 2,650]
        - Memory available: [e.g., 64GB]
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Paste relevant log output here
      render: shell
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
